name: Scheduled Hello World

on:
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Say Hello World
        run: echo "Hello, World! The time is $(date)"
      
      - name: Print current time
        run: |
          echo "Current time: $(date)"
          echo "This workflow was triggered manually using workflow_dispatch"