name: Greeting and Time Workflow
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, world!"
      - name: Say current time
        run: date
      - name: Say goodbye
        run: echo "Goodbye, world!"