on:
  schedule:
    - cron: '*/5 * * * *'

workflow_dispatch:
  jobs:
    hello_world:
      runs-on: ubuntu-latest
      steps:
        - name: Say hello
          run: echo "Hello, world! Now is $(date)"